In [69]:
import pandas as pd
import numpy as np
import matplotlib .pyplot as plt
import matplotlib.image as mpimg

In [70]:
import cv2 
import os 
import glob  
img_dir = r"C:\Users\Umar\image1" # Enter Directory of all images  
data_path = os.path.join(img_dir,'*g') 
files = glob.glob(data_path) 
data = [] 
for f1 in files: 
    img = cv2.imread(f1) 
    img.resize((200,200,1))
    data.append(img) 

In [71]:
data

[array([[[ 57],
         [ 57],
         [ 57],
         ...,
         [ 67],
         [ 61],
         [ 58]],
 
        [[ 67],
         [ 61],
         [ 58],
         ...,
         [ 61],
         [ 70],
         [ 64]],
 
        [[ 61],
         [ 70],
         [ 64],
         ...,
         [ 62],
         [ 60],
         [ 66]],
 
        ...,
 
        [[ 68],
         [ 77],
         [ 71],
         ...,
         [ 76],
         [ 74],
         [ 80]],
 
        [[ 76],
         [ 75],
         [ 79],
         ...,
         [168],
         [ 67],
         [ 98]],
 
        [[151],
         [ 48],
         [ 74],
         ...,
         [ 71],
         [ 77],
         [ 73]]], dtype=uint8),
 array([[[  0],
         [  2],
         [ 29],
         ...,
         [245],
         [112],
         [231]],
 
        [[255],
         [ 85],
         [222],
         ...,
         [  6],
         [ 31],
         [  1]],
 
        [[  6],
         [ 31],
         [  2],
         ...,
      

In [72]:
import cv2 
import os 
import glob 
img_dirs = r"C:\Users\Umar\image2" # Enter Directory of all images  
data_paths = os.path.join(img_dirs,'*g') 
filess = glob.glob(data_paths) 
data1 = [] 
for f1 in filess: 
    imgs = cv2.imread(f1) 
    imgs.resize((200,200,1))
    data1.append(imgs) 

In [73]:
data1

[array([[[ 87],
         [101],
         [130],
         ...,
         [ 79],
         [101],
         [103]],
 
        [[104],
         [ 90],
         [ 92],
         ...,
         [113],
         [119],
         [141]],
 
        [[141],
         [147],
         [143],
         ...,
         [ 85],
         [ 98],
         [130]],
 
        ...,
 
        [[  3],
         [  9],
         [  1],
         ...,
         [139],
         [159],
         [206]],
 
        [[143],
         [161],
         [208],
         ...,
         [  7],
         [  5],
         [  6]],
 
        [[  4],
         [  0],
         [  1],
         ...,
         [141],
         [177],
         [124]]], dtype=uint8),
 array([[[150],
         [178],
         [189],
         ...,
         [202],
         [168],
         [196]],
 
        [[203],
         [168],
         [196],
         ...,
         [ 36],
         [ 41],
         [ 81]],
 
        [[ 87],
         [ 92],
         [ 24],
         ...,
      

In [74]:
x=data+data1

x

[array([[[ 57],
         [ 57],
         [ 57],
         ...,
         [ 67],
         [ 61],
         [ 58]],
 
        [[ 67],
         [ 61],
         [ 58],
         ...,
         [ 61],
         [ 70],
         [ 64]],
 
        [[ 61],
         [ 70],
         [ 64],
         ...,
         [ 62],
         [ 60],
         [ 66]],
 
        ...,
 
        [[ 68],
         [ 77],
         [ 71],
         ...,
         [ 76],
         [ 74],
         [ 80]],
 
        [[ 76],
         [ 75],
         [ 79],
         ...,
         [168],
         [ 67],
         [ 98]],
 
        [[151],
         [ 48],
         [ 74],
         ...,
         [ 71],
         [ 77],
         [ 73]]], dtype=uint8),
 array([[[  0],
         [  2],
         [ 29],
         ...,
         [245],
         [112],
         [231]],
 
        [[255],
         [ 85],
         [222],
         ...,
         [  6],
         [ 31],
         [  1]],
 
        [[  6],
         [ 31],
         [  2],
         ...,
      

In [75]:
x=np.array(x)
x

array([[[[ 57],
         [ 57],
         [ 57],
         ...,
         [ 67],
         [ 61],
         [ 58]],

        [[ 67],
         [ 61],
         [ 58],
         ...,
         [ 61],
         [ 70],
         [ 64]],

        [[ 61],
         [ 70],
         [ 64],
         ...,
         [ 62],
         [ 60],
         [ 66]],

        ...,

        [[ 68],
         [ 77],
         [ 71],
         ...,
         [ 76],
         [ 74],
         [ 80]],

        [[ 76],
         [ 75],
         [ 79],
         ...,
         [168],
         [ 67],
         [ 98]],

        [[151],
         [ 48],
         [ 74],
         ...,
         [ 71],
         [ 77],
         [ 73]]],


       [[[  0],
         [  2],
         [ 29],
         ...,
         [245],
         [112],
         [231]],

        [[255],
         [ 85],
         [222],
         ...,
         [  6],
         [ 31],
         [  1]],

        [[  6],
         [ 31],
         [  2],
         ...,
         [  8],
         [

In [76]:
o=np.stack([1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1])
z=np.stack([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

In [77]:
y=np.append(o,z)
y=np.array(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [78]:
y.shape

(40,)

In [79]:
from tensorflow.keras.utils import to_categorical

In [80]:
y=to_categorical(y)
y

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [81]:
from sklearn.model_selection import train_test_split

In [82]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,shuffle=True,random_state=150)

In [83]:
xtrain.shape

(32, 200, 200, 1)

In [84]:
ytrain.shape

(32, 2)

In [85]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [86]:
from tensorflow.keras.layers import Conv2D, Dense,MaxPooling2D
from tensorflow.keras.layers import Dropout,BatchNormalization


In [87]:
from tensorflow.keras.layers import Flatten

In [88]:
xtrain.shape

(32, 200, 200, 1)

In [89]:
new=Sequential()

new.add(Conv2D(16,(3,3),input_shape=(200,200,1)))
new.add(Conv2D(8,(3,3),activation="relu"))
new.add(MaxPooling2D(2,2))

new.add(Conv2D(8,(3,3),activation="relu"))
new.add(Conv2D(8,(3,3),activation="relu"))
new.add(MaxPooling2D(2,2))

new.add(Conv2D(2,(3,3),activation="relu"))
new.add(Conv2D(8,(3,3),activation="relu"))
new.add(MaxPooling2D(2,2))

new.add(Conv2D(2,(3,3),activation="relu"))
new.add(Conv2D(8,(3,3),activation="relu"))
new.add(MaxPooling2D(2,2))

new.add(Conv2D(2,(3,3),activation="relu"))
new.add(Conv2D(8,(3,3),activation="relu"))
new.add(MaxPooling2D(2,2))


new.add(Flatten())

new.add(Dense(8,activation="relu"))

new.add(Dense(2,activation="sigmoid"))

new.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
new.summary()



Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_12 (Conv2D)           (None, 198, 198, 16)      160       
_________________________________________________________________
conv2d_13 (Conv2D)           (None, 196, 196, 8)       1160      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 98, 98, 8)         0         
_________________________________________________________________
conv2d_14 (Conv2D)           (None, 96, 96, 8)         584       
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 94, 94, 8)         584       
_________________________________________________________________
max_pooling2d_10 (MaxPooling (None, 47, 47, 8)         0         
_________________________________________________________________
conv2d_16 (Conv2D)           (None, 45, 45, 2)        

In [93]:
new.fit(xtrain , ytrain , validation_split=0.1 , epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 137ms/step - loss: 0.3262 - accuracy: 0.9286 - val_loss: 0.7690 - val_accuracy: 0.5000
Epoch 2/50
1/1 [==============================] - 0s 62ms/step - loss: 0.3122 - accuracy: 0.9286 - val_loss: 0.7349 - val_accuracy: 0.5000
Epoch 3/50
1/1 [==============================] - 0s 68ms/step - loss: 0.2994 - accuracy: 0.9643 - val_loss: 0.7469 - val_accuracy: 0.5000
Epoch 4/50
1/1 [==============================] - 0s 65ms/step - loss: 0.2831 - accuracy: 0.9643 - val_loss: 0.7912 - val_accuracy: 0.5000
Epoch 5/50
1/1 [==============================] - 0s 65ms/step - loss: 0.2690 - accuracy: 0.9643 - val_loss: 0.8306 - val_accuracy: 0.5000
Epoch 6/50
1/1 [==============================] - 0s 65ms/step - loss: 0.2552 - accuracy: 1.0000 - val_loss: 0.8289 - val_accuracy: 0.5000
Epoch 7/50
1/1 [==============================] - 0s 63ms/step - loss: 0.2417 - accuracy: 1.0000 - val_loss: 0.8013 - val_accuracy: 0.5000
Epoch 8/50
1/1 [==========

In [94]:
new.evaluate(xtest,ytest)

1/1 [==============================] - 0s 3ms/step - loss: 4.2354 - accuracy: 0.3750


[4.235361099243164, 0.375]

In [95]:
predictions=np.round(new.predict(xtest))
predictions

array([[1., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.]], dtype=float32)

In [96]:
from sklearn.metrics import accuracy_score,confusion_matrix ,classification_report


In [97]:

print(accuracy_score(ytest,predictions))


0.25
